add about
Lana-Malynowska/project-code-crafters pull request #2
Opened 2024-11-18 20:00 UTC by Halyna79

2024-11-19 18:10 UTC, Lana-Malynowska requested changes
декілька змін потрібні

2024-11-19 18:10 UTC, Lana-Malynowska commented on src/css/about-us.css
> +    transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1);
transition прописан,  а де  hover & focus ? зараз немає змін при наведенні

2024-11-19 18:10 UTC, Lana-Malynowska commented on src/css/about-us.css
> +    color: #0c0c0c;
э в глобальних стилях + для посилань у глобальних стилях є "currentColor".  Будь ласка, перевірте, чи це не дублювання  стилів

2024-11-19 18:10 UTC, Lana-Malynowska commented on src/css/about-us.css
> +    cursor: pointer;
у вас це не <button>,  a посилання <a> , тому значення курсор не потрібно

2024-11-19 21:59 UTC, Halyna79 commented
Видалила зайві стилі, щоб не повторювалися, колір не прибирала бо в контейнері прописаний колір аква і він перебиває "currentColor",  курсор-поінтер не прибирала бо то в мене посилання в тегу ( а),  ховер у мене
був, а фокус додала все знаходиться на 188 строці знаходиться.

2024-11-19 22:01 UTC, Halyna79 commented
Коміт останній під назвой fixed css.

2024-11-20 10:10 UTC, Lana-Malynowska commented
ок! вибачте що щось не побачила у вашому коді :)
роблю мердж!

2024-11-20 10:11 UTC, Lana-Malynowska approved these changes

2024-11-20 10:20 UTC, merged